# =========================================================
# BUYLOGIC - APPLICATION
# =========================================================

spring.application.name=buylogic

# =========================================================
# SERVER
# =========================================================

server.port=8080

# =========================================================
# POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/buylogic
spring.datasource.username=postgres
spring.datasource.password=Djaltek30

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# SECURITY
# =========================================================

# Spring Security est installé.
# La configuration de sécurité sera ajoutée ensuite
# dans SecurityConfig.

spring.mvc.servlet.path=/api

spring.profiles.active=dev

jwt.secret=CHANGE-ME-BUYLOGIC-SECRET-KEY-AT-LEAST-32-BYTES-LONG
jwt.expiration=86400000