# =========================================================
# BUYLOGIC - APPLICATION
# =========================================================
spring.application.name=buylogic

app.frontend.url=https://www.buylogic.fr

# =========================================================
# SERVER
# =========================================================
# Railway injecte automatiquement sa propre variable PORT, on l'écoute
server.port=${PORT:8080}


# =========================================================
# POSTGRESQL (Récupération auto depuis Railway)
# =========================================================
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# =========================================================
# CLOUDINARY
# =========================================================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# =========================================================
# MAIL (Brevo SMTP / Production)
# =========================================================
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
app.mail.from=${APP_MAIL_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


# Afficher les requêtes SQL dans les logs pour voir quelle requête plante
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Afficher les erreurs globales et la pile d'exécution du serveur
logging.level.root=INFO
logging.level.com.buylogic=DEBUG
logging.level.org.springframework.web=DEBUG

# LOGGING TRACE FOR MAIL
logging.level.org.springframework.mail=TRACE
logging.level.com.sun.mail.smtp=TRACE
logging.level.jakarta.mail=TRACE