# =========================================================
# BUYLOGIC - APPLICATION
# =========================================================

spring.application.name=buylogic

# =========================================================
# SERVER
# =========================================================

server.port=8080

# =========================================================
# POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/buylogic
spring.datasource.username=postgres
spring.datasource.password=Djaltek30

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# SECURITY
# =========================================================

# Spring Security est installé.
# La configuration de sécurité sera ajoutée ensuite
# dans SecurityConfig.

spring.mvc.servlet.path=/api

spring.profiles.active=dev

jwt.secret=CHANGE-ME-BUYLOGIC-SECRET-KEY-AT-LEAST-32-BYTES-LONG
jwt.expiration=86400000


# Cloudinary
cloudinary.cloud_name=aa3jxqtj
cloudinary.api_key=918355365425877
cloudinary.api_secret=RHaEc9qxxJLytwMSxt14AFbpiA8

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=842a23811a2440
spring.mail.password=6cf8251babd433
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optionnel : email par défaut pour l'expéditeur
app.mail.from=contact@buylogic.com