spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.application.name=buylogic

app.frontend.url=https://www.buylogic.fr

# SERVER
server.port=8080

# POSTGRESQL 
spring.datasource.url=jdbc:postgresql://localhost:5432/buylogic
spring.datasource.username=postgres
spring.datasource.password=Djaltek30
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT 
jwt.secret=9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f
jwt.expiration=86400000

# CLOUDINARY 
cloudinary.cloud_name=aa3jxqtj
cloudinary.api_key=ta_api_918355365425877key
cloudinary.api_secret=RHaEc9qxxJLytwMSxt14AFbpiA8

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# MAIL 
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=d767bb4c27ebdc07d6250fb2cb4ffaea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=hello@www.buylogic.fr

# LOGGING TRACE
logging.level.org.springframework.mail=TRACE
logging.level.com.sun.mail.smtp=TRACE
logging.level.jakarta.mail=TRACE
logging.level.com.buylogic=TRACE